name: smartnotes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  google_sign_in: ^6.2.1
  sqflite: ^2.3.3
  path: ^1.9.0
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  http: ^1.4.0
  intl: ^0.18.1 # Add this line to include the intl package
  path_provider: ^2.1.1
  audioplayers: ^5.0.0
  provider: ^6.1.5
  camera: ^0.10.5+9
  google_mlkit_text_recognition: ^0.10.0
  permission_handler: ^11.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png