// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZyzx44UnAlr19XkcED628vEgqcs_VF5c',
    appId: '1:286338213897:web:8933bea024ff8b221a30d8',
    messagingSenderId: '286338213897',
    projectId: 'smartnotes-c419c',
    authDomain: 'smartnotes-c419c.firebaseapp.com',
    storageBucket: 'smartnotes-c419c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvlPKsYmr-GXPza-cFKTiupc6yDhpk9cU',
    appId: '1:286338213897:android:2490102a81871d9b1a30d8',
    messagingSenderId: '286338213897',
    projectId: 'smartnotes-c419c',
    storageBucket: 'smartnotes-c419c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtvPKkxit0tx2fETpc8hUnGKSIxdTMvNQ',
    appId: '1:286338213897:ios:2fee6b8e1b55a0841a30d8',
    messagingSenderId: '286338213897',
    projectId: 'smartnotes-c419c',
    storageBucket: 'smartnotes-c419c.firebasestorage.app',
    iosBundleId: 'com.example.smartnotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtvPKkxit0tx2fETpc8hUnGKSIxdTMvNQ',
    appId: '1:286338213897:ios:2fee6b8e1b55a0841a30d8',
    messagingSenderId: '286338213897',
    projectId: 'smartnotes-c419c',
    storageBucket: 'smartnotes-c419c.firebasestorage.app',
    iosBundleId: 'com.example.smartnotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZyzx44UnAlr19XkcED628vEgqcs_VF5c',
    appId: '1:286338213897:web:568bbfb1fd38578b1a30d8',
    messagingSenderId: '286338213897',
    projectId: 'smartnotes-c419c',
    authDomain: 'smartnotes-c419c.firebaseapp.com',
    storageBucket: 'smartnotes-c419c.firebasestorage.app',
  );

}